name: 'PR build pipeline'
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18.x
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm

      - name: Cache
        id: cache-modules
        uses: actions/cache@v3.2.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: './node_modules'
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json', './package.json') }}

      - name: 'Install dependencies'
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: 'Run lint'
        run: npm run lint

      - name: 'Run prettier'
        run: npm run prettier

      - name: 'Run audit'
        run: npm run audit

      - name: 'Run build'
        run: npm run ts
